---
title: "NEON forecast challenge submission"
author: 'Aaron Price'
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## In this forecast, I updated the workshop template to include windspeed in the water temperature model. 
## Wind speed was calculated from the eastward and northward wind data

## Link to Git Hub: https://github.com/acpVT/eco_forecast

```{r load-packages, echo = F, warning=F, message=F}
## install.packages('remotes')
## install.packages('fpp3') # package for applying simple forecasting methods
## install.packages('tsibble') # package for dealing with time series data sets and tsibble objects
## install.packages('tidyverse') # collection of R packages for data manipulation, analysis, and visualisation
## install.packages('lubridate') # working with dates and times
## remotes::install_github('eco4cast/neon4cast') # package from NEON4cast challenge organisers to assist with forecast building and submission

# Load packages
library(tidyverse)
library(lubridate)

```

```{r get-targets, message=F}
#read in the targets data
targets <- read_csv('https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz')

# read in the sites data
aquatic_sites <- read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv") |>
  dplyr::filter(aquatics == 1)

lake_sites <- aquatic_sites %>%
  filter(field_site_subtype == 'Lake')

# Filter the targets
targets <- targets %>%
  filter(site_id %in% lake_sites$field_site_id,
         variable == 'temperature')
```

```{r get-NOAA-past, message = F}

# Past stacked weather
noaa_past_s3 <- neon4cast::noaa_stage3()

variables <- c("air_temperature", "eastward_wind", "northward_wind")
#Other variable names can be found at https://projects.ecoforecast.org/neon4cast-docs/Shared-Forecast-Drivers.html#stage-3

noaa_past <- noaa_past_s3  |> 
  dplyr::filter(site_id %in% lake_sites$field_site_id,
                datetime >= ymd('2017-01-01'),
                variable %in% variables) |> 
  dplyr::collect()

# aggregate the past to mean values
noaa_past_mean <- noaa_past |> 
  mutate(datetime = as_date(datetime)) |> 
  group_by(datetime, site_id, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  pivot_wider(names_from = variable, values_from = prediction) |> 
  # convert air temp to C
  mutate(air_temperature = air_temperature - 273.15) |>
  # Calculate wind speed (WS = sqrt (u^2+v^2))
  mutate(wind_speed = sqrt(northward_wind ^ 2 + eastward_wind ^2))


```

```{r get-NOAA-future, message = F}
# Future weather
# New forecast only available at 5am UTC the next day
forecast_date <- Sys.Date() 
noaa_date <- forecast_date - days(2)

noaa_future_s3 <- neon4cast::noaa_stage2(start_date = as.character(noaa_date))
variables <- c("air_temperature", "eastward_wind", "northward_wind")

noaa_future <- noaa_future_s3 |> 
  dplyr::filter(datetime >= forecast_date,
                site_id %in% lake_sites$field_site_id,
                variable %in% variables) |> 
  collect()


noaa_future_daily <- noaa_future |> 
  mutate(datetime = as_date(datetime)) |> 
  # mean daily forecasts at each site per ensemble
  group_by(datetime, site_id, parameter, variable) |> 
  summarize(prediction = mean(prediction)) |>
  pivot_wider(names_from = variable, values_from = prediction) |>
  # convert to Celsius
  mutate(air_temperature = air_temperature - 273.15) |>
  # Calculate wind speed (WS = sqrt (u^2+v^2))
  mutate(wind_speed = sqrt(northward_wind ^ 2 + eastward_wind ^2)) |>
  select(datetime, site_id, air_temperature, eastward_wind, northward_wind, wind_speed, parameter)
```


```{r model-setup}
# Generate a dataframe to fit the model to 
targets_lm <- targets |> 
  filter(variable == 'temperature') |>
  pivot_wider(names_from = 'variable', values_from = 'observation') |> 
  left_join(noaa_past_mean, 
            by = c("datetime","site_id"))

# Loop through each site to fit the model
temp_lm_forecast <- NULL
temp_lm_forecast_PU <- NULL
temp_lm_forecast_IU <- NULL
temp_lm_forecast_PRU <- NULL
```

# Driver Uncertainty 
```{r forecast-loop}
forecast_horizon <- 30
forecast_dates <- seq(from = ymd(forecast_date), to = ymd(forecast_date) + forecast_horizon, by = "day")
n_members <- 31


for(i in 1:length(lake_sites$field_site_id)) {  
  
  curr_site <- lake_sites$field_site_id[i]
  
  # Get only the necessary data for the specific site
  site_target <- targets_lm |>
    filter(site_id == curr_site)

  noaa_future_site <- noaa_future_daily |> 
    filter(site_id == curr_site)
  
  #Fit linear model based on past data: water temperature = m * air temperature + b
  fit <- lm(site_target$temperature ~ site_target$air_temperature + site_target$wind_speed)

  # Loop through all forecast dates
  for (t in 1:length(forecast_dates)) {
  
  #pull driver ensemble for the relevant date; here we are using all 30 NOAA ensemble members
  site_drivers <- noaa_future_site %>%
    filter(datetime == forecast_dates[t])
  
  # use linear regression to forecast water temperature for each ensemble member
  forecasted_temperature <- fit$coefficients[1] + fit$coefficients[2] * site_drivers$air_temperature + 
    site_drivers$wind_speed * fit$coefficients[3]
    
  # put all the relevant information into a tibble that we can bind together
  curr_site_df <- tibble(datetime = rep(forecast_dates[t], times = n_members),
                         site_id = curr_site,
                         parameter = 1:n_members,
                         prediction = forecasted_temperature,
                         variable = "temperature") #Change this if you are forecasting a different variable
  
  temp_lm_forecast <- dplyr::bind_rows(temp_lm_forecast, curr_site_df)
  
  }
  
  message(curr_site, ' forecast run')
}
```

# Parameter Uncertainty 
```{r, warning = FALSE}
forecast_horizon <- 30
forecast_dates <- seq(from = ymd(forecast_date), to = ymd(forecast_date) + forecast_horizon, by = "day")
n_members <- 31


for(i in 1:length(lake_sites$field_site_id)) {  
  curr_site <- lake_sites$field_site_id[i]
  
  # Get only the necessary data for the specific site
  site_target <- targets_lm |>
    filter(site_id == curr_site)

  noaa_future_site <- noaa_future_daily |> 
    filter(site_id == curr_site)
  
  #Fit linear model based on past data: water temperature = m * air temperature + b
  fit <- lm(site_target$temperature ~ site_target$air_temperature + site_target$wind_speed)
  fit_summary <- summary(fit)
  
  coeffs <- round(fit$coefficients, 2)
  params_se <- fit_summary$coefficients[,2]
  
  param.df <- data.frame(beta1 = rnorm(30, coeffs[1], params_se[1]),
                 beta2 = rnorm(30, coeffs[2], params_se[2]),
                 beta3 = rnorm(30, coeffs[3], params_se[3]))
  
  # Loop through all forecast dates
  for (t in 1:length(forecast_dates)) {
  
  #pull driver ensemble for the relevant date; here we are using all 30 NOAA ensemble members
  site_drivers <- noaa_future_site %>%
    filter(datetime == forecast_dates[t])
  
  # use linear regression to forecast water temperature for each ensemble member
  forecasted_temperature <- param.df$beta1 + param.df$beta2 * site_drivers$air_temperature + 
    site_drivers$wind_speed * param.df$beta3
    
  # put all the relevant information into a tibble that we can bind together
  curr_site_df <- tibble(datetime = rep(forecast_dates[t], times = n_members),
                         site_id = curr_site,
                         parameter = 1:n_members,
                         prediction = forecasted_temperature,
                         variable = "temperature") #Change this if you are forecasting a different variable
  
  temp_lm_forecast_PU <- dplyr::bind_rows(temp_lm_forecast_PU, curr_site_df)
  
  }
  
  message(curr_site, ' forecast run')
}

forecast_horizon <- 30
forecast_dates <- seq(from = ymd(forecast_date), to = ymd(forecast_date) + forecast_horizon, by = "day")
n_members <- 31


for(i in 1:length(lake_sites$field_site_id)) {  
  
  curr_site <- lake_sites$field_site_id[i]
  
  # Get only the necessary data for the specific site
  site_target <- targets_lm |>
    filter(site_id == curr_site)

  noaa_future_site <- noaa_future_daily |> 
    filter(site_id == curr_site)
  
  #Fit linear model based on past data: water temperature = m * air temperature + b
  fit <- lm(site_target$temperature ~ site_target$air_temperature + site_target$wind_speed)
  fit_summary <- summary(fit)

  # Loop through all forecast dates
  for (t in 1:length(forecast_dates)) {
  
  #pull driver ensemble for the relevant date; here we are using all 30 NOAA ensemble members
  site_drivers <- noaa_future_site %>%
    filter(datetime == forecast_dates[t])

  residuals <- fit$residuals
  sigma <- sd(residuals, na.rm = TRUE)

  
  # use linear regression to forecast water temperature for each ensemble member
  forecasted_temperature <- fit$coefficients[1] + fit$coefficients[2] * site_drivers$air_temperature + 
    site_drivers$wind_speed * fit$coefficients[3] + rnorm(30, mean = 0, sd = sigma)
    
  # put all the relevant information into a tibble that we can bind together
  curr_site_df <- tibble(datetime = rep(forecast_dates[t], times = n_members),
                         site_id = curr_site,
                         parameter = 1:n_members,
                         prediction = forecasted_temperature,
                         variable = "temperature") #Change this if you are forecasting a different variable
  
  temp_lm_forecast_PRU <- dplyr::bind_rows(temp_lm_forecast_PRU, curr_site_df)
  
  }
  
  message(curr_site, ' forecast run')
}
```


```{r}
# Make forecast fit the EFI standards
# Remember to change the model_id when you make changes to the model structure!
my_model_id <- 'example_ACP_sp24'

temp_lm_forecast_EFI <- temp_lm_forecast %>%
  filter(datetime > forecast_date) %>%
  mutate(model_id = my_model_id,
         reference_datetime = forecast_date,
         family = 'ensemble',
         parameter = as.character(parameter)) %>%
  select(datetime, reference_datetime, site_id, family, parameter, variable, prediction, model_id)

temp_lm_forecast_EFI$uc_type <- "Driver"

```

```{r}
# Make forecast fit the EFI standards
# Remember to change the model_id when you make changes to the model structure!
my_model_id <- 'example_ACP_sp24_PU'

temp_lm_forecast_EFI_PU <- temp_lm_forecast_PU %>%
  filter(datetime > forecast_date) %>%
  mutate(model_id = my_model_id,
         reference_datetime = forecast_date,
         family = 'ensemble',
         parameter = as.character(parameter)) %>%
  select(datetime, reference_datetime, site_id, family, parameter, variable, prediction, model_id)

temp_lm_forecast_EFI_PU$uc_type <- "Parameter"
```

```{r}
my_model_id <- 'example_ACP_sp24_PU'
temp_lm_forecast_EFI_PRU <- temp_lm_forecast_PRU %>%
  filter(!is.na(prediction)) %>%
  filter(datetime > forecast_date) %>%
  mutate(model_id = my_model_id,
         reference_datetime = forecast_date,
         family = 'ensemble',
         parameter = as.character(parameter)) %>%
  select(datetime, reference_datetime, site_id, family, parameter, variable, prediction, model_id)

temp_lm_forecast_EFI_PRU$uc_type <- "Process"
```

```{r}
temp_lm_forecast_EFI_combined <- rbind(temp_lm_forecast_EFI, 
                                   temp_lm_forecast_EFI_PRU, 
                                   temp_lm_forecast_EFI_PU)
```

```{r write-forecast}
# Write the forecast to file
theme <- 'aquatics'
date <- temp_lm_forecast_EFI_combined$reference_datetime[1]
forecast_name_1 <- paste0(temp_lm_forecast_EFI$model_id[1], ".csv")
forecast_file_1 <- paste(theme, date, forecast_name_1, sep = '-')
forecast_file_1


if (!dir.exists('Forecasts')) {
  dir.create('Forecasts')
}

write_csv(temp_lm_forecast_EFI, file.path('Forecasts',forecast_file_1))

neon4cast::forecast_output_validator(file.path('Forecasts',forecast_file_1))

```


```{r submit-forecast}

## # can uses the neon4cast::forecast_output_validator() to check the forecast is in the right format

# UNCOMMMENT THIS WHEN YOU ARE READY TO SUBMIT
neon4cast::submit(forecast_file = file.path('Forecasts', forecast_file_1),
                   ask = T) 
#if ask = T (default), it will produce a pop-up box asking if you want to submit


```

```{r}
temp_lm_forecast_EFI|> 
  ggplot(aes(x=datetime, y=prediction, group = parameter)) +
  geom_line() +
  facet_wrap(~site_id) +
  labs(title = paste0('Forecast generated for ', temp_lm_forecast_EFI$variable[1], ' on ', temp_lm_forecast_EFI$reference_datetime[1]))
```

```{r}
temp_lm_forecast_EFI_PU |> 
  ggplot(aes(x=datetime, y=prediction, group = parameter)) +
  geom_line() +
  facet_wrap(~site_id) +
  labs(title = paste0('Forecast generated for ', temp_lm_forecast_EFI_PU$variable[1], ' on ', temp_lm_forecast_EFI_PU$reference_datetime[1]))
```

```{r, echo = F, warning = F}
temp_lm_forecast_PU %>% 
  filter(variable == 'temperature') %>%
  ggplot(.,aes(x=datetime, y=prediction, group = parameter)) + 
  geom_point(data = targets,aes(x=datetime, y=observation, group = 'obs'), colour = 'darkblue') +
  geom_line(alpha = 0.3, aes(colour = 'ensemble member (parameter)')) + 
  facet_wrap(~site_id, scales = 'free_y') +
  scale_x_date(expand = c(0,0), date_labels = "%d %b") +
  labs(y = 'value') +
  geom_vline(aes(linetype = 'reference_datetime', xintercept = Sys.Date()), colour = 'blue', size = 1.5) +
  labs(title = 'site_id', subtitle = 'variable = temperature', caption = 'prediction') + 
  annotate("text", x = Sys.Date() - days(10), y = 20, label = "past")  +
  annotate("text", x = Sys.Date() + days(12), y = 20, label = "future")  +
  theme_bw() +
  coord_cartesian(xlim = c(min(temp_lm_forecast$datetime) - 15,
                           Sys.Date() + 30)) +
  scale_linetype_manual(values = 'dashed', name = '') +
  scale_colour_manual(values = 'darkgrey', name = '') +
  theme(strip.text = element_text(colour = 'orange'),
        axis.title.y = element_text(colour = 'green'),
        axis.title.x = element_text(colour = 'red'),
        axis.text.y = element_text(colour = 'purple'),
        axis.text.x = element_text(colour = 'red'),
        plot.caption = element_text(hjust = 0, colour = 'purple'),
        plot.title = element_text(colour = 'orange'), 
        plot.subtitle = element_text(colour = 'green')) 
```

